version: "3.9"

services:
  # php
  app:
    image: 'php81'
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/web
    working_dir: /var/www/web
    networks:
      - app-network

  # web server
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/web
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - app-network

  # database
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
      MYSQL_ROOT_PASSWORD: root_pass
    networks:
      - app-network

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www/web
    working_dir: /var/www/web
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - app-network

# docker networks
networks:
  app-network:
    driver: bridge
